# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 397)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Nickname = QtWidgets.QLineEdit(self.centralwidget)
        self.Nickname.setGeometry(QtCore.QRect(60, 10, 631, 20))
        self.Nickname.setObjectName("Nickname")
        self.go = QtWidgets.QPushButton(self.centralwidget)
        self.go.setGeometry(QtCore.QRect(700, 10, 71, 21))
        self.go.setObjectName("go")
        self.YourNickname = QtWidgets.QLabel(self.centralwidget)
        self.YourNickname.setGeometry(QtCore.QRect(10, 10, 47, 21))
        self.YourNickname.setObjectName("YourNickname")
        self.SeenFilms = QtWidgets.QLabel(self.centralwidget)
        self.SeenFilms.setGeometry(QtCore.QRect(10, 120, 111, 21))
        self.SeenFilms.setObjectName("SeenFilms")
        self.SeenFilmsVal = QtWidgets.QLCDNumber(self.centralwidget)
        self.SeenFilmsVal.setGeometry(QtCore.QRect(170, 120, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SeenFilmsVal.setFont(font)
        self.SeenFilmsVal.setObjectName("SeenFilmsVal")
        self.WishFilms = QtWidgets.QLabel(self.centralwidget)
        self.WishFilms.setGeometry(QtCore.QRect(10, 150, 151, 21))
        self.WishFilms.setObjectName("WishFilms")
        self.WishFilmsVal = QtWidgets.QLCDNumber(self.centralwidget)
        self.WishFilmsVal.setGeometry(QtCore.QRect(170, 150, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.WishFilmsVal.setFont(font)
        self.WishFilmsVal.setSmallDecimalPoint(False)
        self.WishFilmsVal.setObjectName("WishFilmsVal")
        self.LikeFilms = QtWidgets.QLabel(self.centralwidget)
        self.LikeFilms.setGeometry(QtCore.QRect(10, 180, 101, 21))
        self.LikeFilms.setObjectName("LikeFilms")
        self.LikeFilmsVal = QtWidgets.QLCDNumber(self.centralwidget)
        self.LikeFilmsVal.setGeometry(QtCore.QRect(170, 180, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LikeFilmsVal.setFont(font)
        self.LikeFilmsVal.setObjectName("LikeFilmsVal")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 210, 801, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 100, 801, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.WishSerialsVal = QtWidgets.QLCDNumber(self.centralwidget)
        self.WishSerialsVal.setGeometry(QtCore.QRect(170, 290, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.WishSerialsVal.setFont(font)
        self.WishSerialsVal.setObjectName("WishSerialsVal")
        self.SeenSerials = QtWidgets.QLabel(self.centralwidget)
        self.SeenSerials.setGeometry(QtCore.QRect(10, 260, 111, 21))
        self.SeenSerials.setObjectName("SeenSerials")
        self.SeenSerialsVal = QtWidgets.QLCDNumber(self.centralwidget)
        self.SeenSerialsVal.setGeometry(QtCore.QRect(170, 260, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SeenSerialsVal.setFont(font)
        self.SeenSerialsVal.setObjectName("SeenSerialsVal")
        self.WishSerials = QtWidgets.QLabel(self.centralwidget)
        self.WishSerials.setGeometry(QtCore.QRect(10, 290, 151, 21))
        self.WishSerials.setObjectName("WishSerials")
        self.LikeSerialsVal = QtWidgets.QLCDNumber(self.centralwidget)
        self.LikeSerialsVal.setGeometry(QtCore.QRect(170, 320, 61, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LikeSerialsVal.setFont(font)
        self.LikeSerialsVal.setObjectName("LikeSerialsVal")
        self.LikeSerials = QtWidgets.QLabel(self.centralwidget)
        self.LikeSerials.setGeometry(QtCore.QRect(10, 320, 101, 21))
        self.LikeSerials.setObjectName("LikeSerials")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 230, 801, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 80, 801, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.StoppedSerials = QtWidgets.QLabel(self.centralwidget)
        self.StoppedSerials.setGeometry(QtCore.QRect(10, 350, 151, 21))
        self.StoppedSerials.setObjectName("StoppedSerials")
        self.StoppedSerialsVal = QtWidgets.QLCDNumber(self.centralwidget)
        self.StoppedSerialsVal.setGeometry(QtCore.QRect(170, 350, 61, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.StoppedSerialsVal.setFont(font)
        self.StoppedSerialsVal.setObjectName("StoppedSerialsVal")
        self.PatchToSave = QtWidgets.QLineEdit(self.centralwidget)
        self.PatchToSave.setGeometry(QtCore.QRect(90, 40, 521, 20))
        self.PatchToSave.setObjectName("PatchToSave")
        self.PatchLabel = QtWidgets.QLabel(self.centralwidget)
        self.PatchLabel.setGeometry(QtCore.QRect(10, 40, 101, 21))
        self.PatchLabel.setObjectName("PatchLabel")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(620, 40, 69, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.OpenPatch = QtWidgets.QPushButton(self.centralwidget)
        self.OpenPatch.setGeometry(QtCore.QRect(700, 40, 71, 21))
        self.OpenPatch.setObjectName("OpenPatch")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MovieLibSaver"))
        self.go.setText(_translate("MainWindow", "Начать"))
        self.YourNickname.setText(_translate("MainWindow", "Ваш ник"))
        self.SeenFilms.setText(_translate("MainWindow", "Я посмотрел фильмы"))
        self.WishFilms.setText(_translate("MainWindow", "Я хочу посмотреть фильмы"))
        self.LikeFilms.setText(_translate("MainWindow", "Любимые фильмы"))
        self.label.setText(_translate("MainWindow", "Фильмы"))
        self.SeenSerials.setText(_translate("MainWindow", "Я посмотрел сериалы"))
        self.WishSerials.setText(_translate("MainWindow", "Я хочу посмотреть сериалы"))
        self.LikeSerials.setText(_translate("MainWindow", "Любимые сериалы"))
        self.label_2.setText(_translate("MainWindow", "Сериалы"))
        self.StoppedSerials.setText(_translate("MainWindow", "Перестал смотреть сериалы"))
        self.PatchLabel.setText(_translate("MainWindow", "Путь к файлу"))
        self.comboBox.setItemText(0, _translate("MainWindow", "DOCX"))
        self.comboBox.setItemText(1, _translate("MainWindow", "DOC"))
        self.comboBox.setItemText(2, _translate("MainWindow", "RTF"))
        self.OpenPatch.setText(_translate("MainWindow", "Открыть"))
